name: friends_tournament
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_svg: ^0.17.4
  rxdart: ^0.24.1
  sqflite: ^1.3.0+2
  flare_flutter: ^2.0.3
  google_fonts: ^1.1.0
  sentry: ">=3.0.0 <4.0.0"

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  sqflite_common_ffi: 1.0.0+2
  synchronized: '>=2.0.2 <4.0.0'

flutter:
  uses-material-design: true

  assets:
    - intro-art.svg
    - players_art.svg
    - player-ast-art.svg
    - matches-art.svg
    - podium-art.svg
    - save-art.svg
    - finish-art.svg
    - error-art.svg
    - winner-art.svg
    - lang/en.json
    - lang/it.json

  fonts:
   - family:  CustomIcons
     fonts:
      - asset: fonts/CustomIcons.ttf
